// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { SpawnInputs, ZKProof } from "./../../libraries/LibSeismic.sol";

/**
 * @title IPlayerRegisterSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPlayerRegisterSystem {
  function register(bytes32 matchEntity, uint256 spawnIndex, bytes32 heroChoice) external returns (bytes32);

  function registerFOW(SpawnInputs calldata spawnInputs, ZKProof calldata spawnProof) external returns (bytes32 player);
}
